### ISSUE TITLE
Database - [User] structure

### ISSUE THREAD

**Issue by tylerjwatson** [NyxStudios/Orion#10]
## Rationale

TShock's current database system for  users currently lacks keys and aren't relational.  Key identifying credentials such as IP addresses and UUIDs are hacked on in JSON/text columns and aren't useful for a proper SQL relational db.

Many-to-many with [UUID] means that one user may have many UUIDs, and may log in to any account they have been previously bound with by using `/login accountname`, and UUID reporting becomes very easy, you can now query the database for every [User] that has ever logged in under a specified [UUID].

Many-to-many with [IPAddress] follows the same pattern.  It's easy to report on any IP address who has connected to the server, and along with any TShock account they have touched.  Conversely, you can report on any IP address who has touched a single TShock account.
## Structure
- [User] Table
  - ID - Primary Key
  - Name - user's account name
  - PasswordHash - self explanatory
  - RegisteredAt - Date account registered
  - LastAccessedAt - Date account was last accessed
  - AllowAccess - Specifically deny access to this account
- [IPAddress] table
  - ID primary key
  - IPv4Long - long binary representation of IPv4 address - index unique
  - IPv4String - string representation of IPv4 addr
- [UserHasGroup] joiner table:
  - UserFK Primary Key references [User] cascade
  - GroupFK Primary Key references [Group] cascade
- [UserHasUUID] joiner table
  - UserFK - Primary Key references [User] cascade
  - UUIDFK - Primary key references [UUID] cascade
- [UserHasIPAddress] joiner table
  - UserFK primary key references [User] cascade
  - IPAddressFK - Primary key references [IPAddress] cascade

**Comment by QuiCM** [comment]
What's the purpose of the IPv4String in the IPAddress table?

**Comment by tylerjwatson** [comment]
IPv4String is just there so people can query the database against a normal IP address string, since a lot aren't going to know how to convert between an IPv4 long and its dotted quad notation.

IPv4 long is there because of performance and queryability.

It's purely for looks, and can be removed if need be.

**Comment by QuiCM** [comment]
My opinion is remove string and just leave the long. We can provide methods for converting between the two inside the codebase

**Comment by tylerjwatson** [comment]
Yeh can do.

**Comment by Ijwu** [comment]
Is there a UUID table missing?

**Comment by tylerjwatson** [comment]
Indeed there is haha
