### ISSUE TITLE
Framework - OrionModule transparent configuration system

### ISSUE THREAD

**Issue by tylerjwatson** [NyxStudios/Orion#13]
## Rationale

Moving to a modular system in orion paves the way for transparent configuration, so we may as well use it.  Configuration is a pain point for current plugin developers.

The proposed architecture makes it possible for plugins to store their configs in a clean and consistent fashion, without the developer ever having to care about the physical files themselves; all they need to care about is their config class in their code is full of human configured values.
## Architecture

I propose that configuration management be perfomed by Orion itself, and not by plugins.  If an Orion module is to have a configuration, it must provide a configuation class inheriting from `OrionModuleConfiguration`, otherwise no configuration for the module is assumed.  

If the configuration doesn't exist, Orion is to create one via the interface, with default values in the class.

This class is to contain regular properties full of arrays and everything that the module needs to configure itself from a human perspective, and Orion fetches configurations during its init/reload phase and provides an instance of the deserialized configuration class to the instance via the `OrionModuleBase` constructor which could have a `OrionModuleConfiguraion config` parameter. Alternatively, `OrionModuleBase` could have a virtual `GetConfiguration<TConfiguration>()` where TConfiguration is the type of class the module has registered.

`OrionModuleConfigurationBase` is to have`Save()`, `Reload()` and any other sensible methods which will tell orion to manipulate config.

Configuration is to come from an `IConfigurationProvider` framework implementation discussed in #12.  It may write to JSON, it may write to XML, it may write to SQL, it may write to REST. it could, in effect, be anything.
## Pathing

TSAPI shall be modified, with the old `Environment.CurrentDirectory` assuming code removed in lieu of a smarter system, particularly for Linux servers which expect configuration to be in `/etc/`.  There must also be a shared plugins directory to help shared hosting providers run only one copy of plugin files.
## File Format

TBD
## Result

Orion plugins only have to write a class full of properties for configuration, and Orion takes care of the rest.
## Others

TODO

**Comment by Ijwu** [comment]
Has been implemented in OTAPI branch. Work on it started here: https://github.com/NyxStudios/Orion/commit/d4df33314fa66baafa51d302b3831e792bbee6f1
