### ISSUE TITLE
[RFC] Service framework: SharedService and Service

### ISSUE THREAD

**Issue by tylerjwatson** [NyxStudios/Orion#24]
Up until now there is only support for one type of service, `IService` which lives in singleton scope.  It has been identified that not all services are fit for a singleton, so two service types must be created.
### Use Case: Multi-injection

There is no reason for `IConfigurationService` to be singleton.  It would be better served as a generic service that takes a type argument for the class that it is to be serializing, to enable multiples of them to be injected into a target.

Consider the following hypothetical plugin:

``` csharp
public class MyPlugin : OrionPlugin {
    public MyPlugin(Orion orion, IConfigurationService<GlobalConfiguration> globalConfig,
        IConfigurationService<WorldConfiguration> worldConfig) : base(orion)
    {
    }
}
```

In this example, `GlobalConfiguration` and `WorldConfiguration` are classes which hold properties for two different configuration elements in a single plugin, and are best stored in two separate files.  Many plugins traditionally use more than one type of configuration so this design is pertinent.

The best use case for non-singleton services would enable the serialization and de-serialization of separate configuration classes, one per service instance.  This would require two types of services to be handled by Orion's injection mechanism

**Comment by QuiCM** [comment]
:+1:

**Comment by tylerjwatson** [comment]
_Updated_

**Comment by Ijwu** [comment]
I agree that the next step with the injection is making the services available in scopes other than singleton scopes. How is this decided, though? Are we just going to move all singleton services to `ISharedService` and bind those in singleton scope?

**Comment by tylerjwatson** [comment]
> Are we just going to move all singleton services to ISharedService and bind those in singleton scope?

depending on class behaviour, yeah that was pretty much the plan.  I may end up going with a `SharedServiceBase` abstract as well depending on if anything else needs to be stored in the class

**Comment by MarioE** [comment]
Is there any reason we can't just simply have a `SharedServiceAttribute` instead, though?

**Comment by kevzhao2** [comment]
Closing this, as it is now outdated compared to the current API.
