### ISSUE TITLE
[RFC] Service framework: External definitions

### ISSUE THREAD

**Issue by tylerjwatson** [NyxStudios/Orion#25]
Until now, Orion only allows service definitions internal to its own assembly.  They are defined by us and essentially hard-coded.  The injector doesn't know how to bind interfaces it doesn't know about.

It's time to have a discussion about extensibility to the service mechanism which will allow the flexibility to create _"foreign"_ service types externally, from assemblies in the `plugins` directory in the same way plugins are harvested.
### User story: custom services

As the author of SEconomy, a plugin that provides a facility (or _service_) to other plugins and extensions, I should have the ability to define my _own_ services in which will be injected into my own plugin, and others.

Consider a hypothetical SEconomy service definition externally in Orion:

``` csharp
public interface IWorldEconomyService : IService
{
}
```

In this design, I define my own world economy service to Orion which is contained in my plugin assembly.  The assembly has its own default implementation which SEconomy will use, but other people may choose to override the service and provide their own world economy.

As long as they implement `IWorldEconomyService`, there is nothing stoping plugins from extending other plugins' functionality.

Consider a hypothetical SEconomy plugin:

``` csharp
public class EXPPlugin(Orion orion, ICurrency<ExpCurrency> currencyService, 
        IWorldEconomyService worldEconomy) : base(orion)
{
    ...
}
```

In this example, `IWorldEconomyService` by default shall point to its own internal implementation of world economy, however doesn't have to.  The same semantics shall apply to `ICurrency<>`, or any service definition.

**Comment by Ijwu** [comment]
How are we going to handle several implementations of the same service? Will this all be configured before runtime? Does this mean a configuration step is required with every plugin installation which handles or introduces a new service?

**Comment by MarioE** [comment]
So, this appears to be partially implemented as of now, since we are currently scanning the plugin directory for services. However, we still have to handle multiple binding and service overriding...
