### ISSUE TITLE
Namespace and type naming collisions

### ISSUE THREAD

**Issue by MarioE** [NyxStudios/Orion#26]
There are a few instances of shared namespace and type names:
- `class Orion` and namespace `Orion`
- `class Item` and namespaces `Orion.Entities.Item`, `Orion.Events.Item`
- `class Npc` and namespaces `Orion.Entities.Npc`, `Orion.Events.Npc`
- `class Player` and namespaces `Orion.Entities.Player`, `Orion.Events.Player`
- `class Projectile` and namespaces `Orion.Entities.Projectile`, `Orion.Events.Projectile`

This could lead to a few annoyances later on, and should probably be fixed now. One solution would be to pluralize `Orion.Entities.<EntityName>` (and place the events in there too, or pluralize that as well). I'm not sure how we should deal with `Orion.Orion`, though.

**Comment by Ijwu** [comment]
I think renaming the `Orion` namespace to something like `OrionApi` is fitting and acceptable.

What about prefixing the entity names? Something like `OrionItem`, `OrionNpc`, etc. That way we have differentiation in the code as from the Terraria entities. (As well as name differentiation).

We can probably then leave the namespaces the same.

**Comment by MarioE** [comment]
I do like prefixing the entity names, but you would still have a conflict with the namespace and the Terraria entity. Since the concrete types are going into TShock, we would name them `TshockItem`, `TshockNpc`, etc.

Also, something to note is that our type names conflicting with Terraria names shouldn't make too much of a difference in our name decisions, since our goal is to eventually have consumers not need to reference anything in the Terraria namespace.

**Comment by Ijwu** [comment]
Prefixing them with `TShock` (or `Tshock`, whatever) is good. I would agree with pluralizing the namespaces. 

Note: Ignore accidental comment+close

**Comment by MarioE** [comment]
If there are no objections to the namespace renaming, then I will do this tonight.

**Comment by Ijwu** [comment]
Please detail the exact changes you'll make, for the sake of having it on record+everyone being on the same page.

**Comment by MarioE** [comment]
- `Orion.*` -> `OrionApi.*`
- `Orion.Entities.<name>` -> `OrionApi.Entities.<name>s`
- `Orion.Events.<name>` -> `OrionApi.Events.<name>s`

EDIT: where `<name>` != `World`
