### ISSUE TITLE
Properly implement IoC

### ISSUE THREAD

**Issue by MarioE** [NyxStudios/Orion#27]
Implement IoC properly, passing around `Func<TTerrariaType, OurType>`s in order to wrap the necessary objects in, e.g., `ItemService`, `PlayerService`, etc.

E.g., `Player` constructor needs to be something like this:

``` c#
public Player(Terraria.Player terrariaPlayer, Func<Terraria.Item, Item> itemWrapper, Func<Terraria.Item[], IItemArray> itemArrayWrapper)
```

**Comment by tylerjwatson** [comment]
I've never seen func delegates in any soa pattern before, why do you need to do this?

**Comment by MarioE** [comment]
Closed for now, see discussion in slack channel.
