### ISSUE TITLE
Feature Request: ChatAboveHeads

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/Orion#29]
Speaks for itself, ChatAboveHeads just as in TShock.

**Comment by Ijwu** [comment]
This is a very pre-emptive feature request, seeing as Orion isn't even out for testing yet. But, I think it's fair enough to state and I think it's fair enough to keep this issue open. 

When we get to that point of Orion I will try to ensure we keep this in mind.

**Comment by kevzhao2** [comment]
This is not actionable and not relevant to Orion. We will revisit this later.
