### ISSUE TITLE
Discussion: Scripting Engine

### ISSUE THREAD

**Issue by Ijwu** [NyxStudios/Orion#37]
C# Scripting is now feasibly possible with the Roslyn Compiler Platform. It could be possible to allow for plugins to be loaded in the form of C# source code files and have them dynamically compiled to assemblies at run-time. This could possibly allow for hot-reloading and runtime edits by removing references to the hot-potato code and recompiling it. 

This is mentioned by @Patrikkk in #35 during our discussion about plugin hot-reloading. A separate discussion about a scripting engine vs. a pre-compiled plugin engine is worth having. Please funnel all scripting engine discussion to this issue.

**Comment by tylerjwatson** [comment]
To be clear, I think we should set the main outcome of the scripting engine to be **reloadable units** that do not require the server to be shut down to be refreshed.

The main issue with C# "scripting" is that they are not _scripts_, and is the main reason why I don't want to support it in Orion:  They do not run in a sandbox in any way and have the same privilege level as anything running in the host process:  They are a _giant_ security risk and should be avoided at all cost.

The main issue with _anything_ that uses the DLR (Roslyn-compiled c# code, Boo, IronPython et al.) is that the code still ends up in the same AppDomain, and cannot be reloaded unless you reboot the process.  Forcing a reload on a DLR assembly will cause leaks at the very best, and can have catastrophic consequences at the worst:  Timers, threads and other deferred mechanisms in the `static` GCroot will continue to run regardless of any `Dispose()` unless  explicitly cleaned up properly from the developer.

**Comment by hakusaro** [comment]
Lua?

**Comment by Ijwu** [comment]
There are options that allow for dynamic execution of code without requiring a 'compile' with the DLR. IronPython does have facilities to run actual scripts. Lua is most definitely an option and I have some experience working with it (many years ago, though).
