### ISSUE TITLE
AAA: Users and Accounts

### ISSUE THREAD

**Issue by AxisKriel** [NyxStudios/Orion#46]
The general consensus in server applications is that each person connecting is given a `User` object. This object serves as the main interaction point between the server and the client. Users may register to the system which creates a user `Account` associated with the user object. Typically, accounts are simply database information that grants the user access to certain features when authenticated to. This issue addresses the nomenclature changes made in a recent commit by defining why we should name our classes in a certain way.

Because Terraria is a game, clients are associated with a `Player` object which controls how the client interacts with the server. We may call this player object our `User`. An Orion player is able to authenticate to a user account to be granted access to that account's settings and permissions. In TShock 4, however, we used a `User` class as a database structure that simply hold information to be stored/retrieved. Users weren't even linked to TSPlayer objects until recently; we'd just store the user id and name on the player object.

Because naming database accounts "User"  can be deceiving, and "UserAccount" is an unnecessarily long name for the context, I suggest the following changes to normalize naming in services:
- Our point of interaction with players remains in the OrionPlayer object and derivatives.
- IUserAccountService organizes the data accounts and validates authentication to them, so its name should change to simply `IAccountService`. This makes it fit better alongside `IGroupService` and `IPermissionService` as we're not prefixing those with `User`.
- Likewise, UserAccount and references should change to simply `Account`, as we can assume they refer to the accounts used by our players. This partially reverts the latest changes by me taking the opposite approach now that conventions have been made clear to me.

A pull request will be made with proper GitHub Flow guidelines applying these changes. Should this be the nomenclature of choice for our AAA services?
_This issue was based on a Slack discussion. Most points have been covered here through a diverse approach._

**Comment by QuiCM** [comment]
:+1: to `Account` and `IAccountService`
