### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by QuiCM** [NyxStudios/Orion#5]
### Orion Core
- [ ] DI/Module Loader Framework
- [x] Log4Net
- [ ] Packet repackaging
- [ ] Storage/Database Framework
- [ ] Module configuration Framework
- [ ] Command framework
- [ ] Console Framework
### TShock v5
- [ ] Bans
- [ ] SSC
- [ ] User storage
- [x] ~~Plugin reloading~~ Likely will not happen
- [ ] Database rewrite
- [ ] REST

**Comment by tylerjwatson** [comment]
NB. Bought this issue up to date a bit.
