### ISSUE TITLE
Discussion: Current State of Orion

### ISSUE THREAD

**Issue by kevzhao2** [NyxStudios/Orion#52]
Since I've pushed a ton of stuff to the `reboot` branch, I want to recap what's been done there.

Orion's goal is to act as an _intermediary_ layer between OTAPI/Terraria and TShock/other plugins. The way in which this is done is by providing interfaces such as `INpc` and `INpcService` to consumers such as TShock. There are three main reasons for this:

- Testability. With interfaces, it's _much_ easier to mock, say, a Terraria NPC than before. This should make all plugins a lot easier to test and less buggy.
- Extensibility. A custom NPCs plugin could create its own implementation of `INpc` by creating its own `INpcService` and allow NPCs to have extra features.
- Compatibility. These interfaces shield customers from any changes in the underlying OTAPI/Terraria server code. Granted, in cases of extreme change, we'll still need to modify the interfaces and break compatibility, but this is at least a step in the right direction.

---

To create a service, you should create an interface that inherits from `IService` and an implementation that inherits from `OrionService` and implements your interface. The `Author`, `Name`, and `Version` properties can be overridden as necessary.
```c#
public interface ICommandService : IService {
    void ExecuteCommand(string input);
}

internal class TShockCommandService : OrionService, ICommandService {
    public void ExecuteCommand(string input) { }
}
```

To create a plugin, your implementation should inherit from `OrionPlugin`. It isn't necessary to create a plugin interface, but you _could_ do that if you wanted to. Your constructor should include all of the plugins and services you'll need, as they'll be injected for you.
```c#
public class WorldEditPlugin : OrionPlugin {
    public override string Author => "Kevin";
    public override string Name => "WorldEdit";

    private readonly IWorldService _worldService;

    public WorldEditPlugin(OrionKernel kernel, IWorldService worldService) : base(kernel) {
        _worldService = worldService ?? throw new ArgumentNullException(nameof(worldService));
    }
}
```

To register a hook, just use `+=` on the relevant `HookHandlerCollection<>` with a valid handler. This is thread-safe since `HookHandlerCollection<>` is immutable.
```c#
_worldService.SavingWorld += SavingWorldHandler

...

[HookHandler(HookPriority.Lowest)]
private void SavingWorldHandler(object sender, SavingWorldEventArgs args) {
}
```

Logging is handled via [Serilog](https://serilog.net/). To log something, just access the static `Log` class:
```c#
Log.Verbose("Verbose message");
Log.Debug("Debug message");
Log.Information("Information message");
Log.Warning("Warning message");
Log.Error("Error message");
Log.Fatal("Fatal message");
```

By default, the Orion launcher sinks this log to the console and a daily rolling file under the `logs/` directory.

---

Listed below is the functionality that Orion currently has. I don't think the services that we offer are going to change any time soon.

- `IItemService`: access `IItem` instances, item-related hooks, and item-related methods (`SpawnItem`, etc.).
- `INetworkService`: access `IClient` instances, network-related hooks, and network-related methods (`BroadcastPacket`, etc.). There is an entire type-safe packet library implemented under `Orion.Networking.Packets` to facilitate usage.
- `INpcService`: access `INpc` instances, NPC-related hooks, and NPC-related methods (`SpawnNpc`, etc.).
- `IPlayerService`: access `IPlayer` instances and player-related hooks.
- `IProjectileService`: access `IProjectile` instances, projectile-related hooks, and projectile-related methods (`SpawnProjectile`, etc.).
- `IChestService`: access `IChest` instances and chest-related methods (`AddChest`, `GetChest`, etc.).
- `ISignService`: access `ISign` instances and sign-related methods (`AddSign`, `GetSign`, etc.).
- `IWorldService` access `Tile` instances, world-related hooks, and world-related methods (`Save`, etc.).

In addition, all objects above are annotatable, allowing users to get or set annotations for each instance. This makes it easy for these objects to be extended.

Orion will not be responsible for providing commands, configurations, or users, groups, or permissions. This is to be handled by plugins such as TShock, and allows Orion to remain as light-weight as possible.

---

If you have any comments or suggestions, please respond with them.

**Comment by kevzhao2** [comment]
One main question I have is whether to continue sticking stuff like `IAccountService`, `ICommandService`, `IRestService`, etc. in Orion. @tylerjwatson @Ijwu @hakusaro @QuiCM @AxisKriel

Shouldn't this now be TShock's job? Why do we need these definitions in Orion now?

**Comment by QuiCM** [comment]
Agreed - account and user management services fall outside the scope of Orion. I believe account/rest/command were originally included so that any tshock alternatives would have base services out of the box that they could use and override/extend if necessary, rather than having to create the entirety of those services themselves

**Comment by kevzhao2** [comment]
> Agreed - account and user management services fall outside the scope of Orion. I believe account/rest/command were originally included so that any tshock alternatives would have base services out of the box that they could use and override/extend if necessary, rather than having to create the entirety of those services themselves

I see. To be honest, I'm not sure there's any point in doing that any more. If TShock alternatives would like to override them, then they probably wanted an entirely different mechanism. I think extensions are possible __as long as we provide events for these services__.

**Comment by kevzhao2** [comment]
For example, as long as the command service provides an `ExecutingCommand` event, then a permission service could hook that and handle the event if the user is determined to not have the required permissions.

**Comment by QuiCM** [comment]
Yep. Sounds reasonable

**Comment by hakusaro** [comment]
For the most part, abstracting for "TShock Alternatives" that don't exist yet it is not a good use of anyone's time. In fact, dare I say that most abstraction that's done before the existence or need of alternatives is not a good plan.

I believe the goal should be to be like Bukkit + CraftBukkit. While an abstract API exists, it at least has one shipping implementation that someone would _want to use_. That means that we shouldn't create a ton of interfaces with prototype implementations that nobody actually would actually use. I would even go so far as to say that this is part of the problem with the project in general. It is certainly advantageous to create interfaces for the purposes of mocking BS from Terraria and testing, but it is also a very big problem to _only_ create interfaces with no concrete implementation and then to call it a day.

**Comment by kevzhao2** [comment]
Yeah, I definitely agree. There's a trade-off between time and "programming pureness". In this case, all of the current (reboot) definitions have _real_ implementations, and most of them (barring the network service, which is a pretty painful thing to write tests for, since Terraria network functionality is basically untestable) have tests.

Stuff like logging, which we were thinking of whipping our own solution for, has already been solved countless times by other people. There's no point in re-creating what [Serilog](https://serilog.net/) can do, for example. There's also no point in trying to pass `ILogger`s and everything around.

**Comment by hakusaro** [comment]
`IAgree`.

**Comment by bartico6** [comment]
While I'm not certain if that is "in plans" or not, I would like to repeat that tShock and its ecosystem should move away from nethooks & nethook usage should be strictly discouraged unless you know what you're doing and you need to mess with netcode directly.  
  
This is because things ideally would be using events, even if they're naive wrappers around nethooks, since in many cases it would be convenient to have events (that other plugins can raise) rather than nethooks and nothing else.  
  
A case study of this is an anticheat I have developed & tested in the past N months - every single check (which is based on packets received) is delayed until more data is available and then those events would be either validated & pushed through or rejected and rolled back. However, for events that pass through at a later date, notifying other plugins (including tshock) is completely impossible because without creating a new message buffer, pushing data into it and running checkbytes or whatever on it you cannot manually fire hooks in other plugins.

**Comment by kevzhao2** [comment]
Yep, that makes sense. I think Orion should expose events for actually everything, tbh. It should expose block breaking, player teleporting, etc.
