### ISSUE TITLE
Database re-write

### ISSUE THREAD

**Issue by QuiCM** [NyxStudios/Orion#7]
Rewrite the database system using [Dapper](https://github.com/StackExchange/dapper-dot-net).
Should preferably conform to relational database standards

cc @ijwu @tylerjwatson

**Comment by tylerjwatson** [comment]
Will definitely conform to an RDBMS.

**Comment by tylerjwatson** [comment]
Suggesting to go with EntityFramework.  It's slightly heavier but has a SQL independent achitecture and we could support really any database that EF does.  Code-first mapping means it'll create schema for you, and migrations means we can make schema changes per releases of orion.

**Comment by Ijwu** [comment]
From what I've seen,  entity framework is really heavy.  The idea with dapper was to just provide the convenience and functionality of the micro orm with the least changes to the existing code.  My initial idea wasn't to fully rewrite as much as to provide some nice shortcuts. 

However,  I'm not against EF. It simply wasn't the initial idea and not the amount of work I was prepared to invest.  I'll simply allot more free time to wire up EF.

TDSM also uses EF and I'll have their stuff as a relevant example.

**Comment by tylerjwatson** [comment]
oh, i'd already started. haha

EF6 is not that heavy, I can use it to pull about 50k rows in ~40-50ms depending on backend.  It's worth it so that we don't have to write and freeze schema.

Are you in charge of schema? I have started to rewrite it.  If shortcuts are the goal here and not actual reimplementation of the database then I will step out.

**Comment by tylerjwatson** [comment]
PS. If we are going with OWIN for the REST frontend get used to taking on some well heavy stuff. :)

**Comment by Ijwu** [comment]
Haha,  I'm not so much in charge of the new schema as much as I was the sucker who first volunteered. I'm totally behind the full rewrite. Please don't step out. I haven't had a chance to actually write code in the past few days. I'm helping my buddy move into his new place and things are busy.

**Comment by tylerjwatson** [comment]
I will at least do a new schema because the current one blows a lot of chunks, the DAL we use to get access to this info can be decided later - I will rip out EF when needed.

I don't mind DB and DAL work since I have done it most of my career.

**Comment by Ijwu** [comment]
Awesome.  +1

I don't have any serious misgivings about EF so don't rush to rip it out. I doubt I'd be able to poke any holes in the idea.

**Comment by QuiCM** [comment]
https://github.com/NyxStudios/Orion/issues/7#issuecomment-139832514

Orion is basically about reimplementing everything. Out with the old, in with the new!

**Comment by tylerjwatson** [comment]
It looks like EF requires slightly separate code for each SQL provider we are to support which is fairly disappointing.  

Are we okay with this?

**Comment by Ijwu** [comment]
I'm ok with it. So far the only dialects we need to support are MySql and Sqlite. Others can be added in over time if need be.

**Comment by QuiCM** [comment]
That's fine. The old system required different code as well
